# Generated by Django 5.1.4 on 2025-11-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_borrower_email_alter_borrower_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
