# Generated by Django 5.1.4 on 2025-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_borrower_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='receipt_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='receipt_serial',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
