# Generated by Django 5.1.4 on 2025-11-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_receipt_hash_loan_receipt_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='back_id',
            field=models.ImageField(blank=True, null=True, upload_to='borrower_ids/'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='front_id',
            field=models.ImageField(blank=True, null=True, upload_to='borrower_ids/'),
        ),
        migrations.CreateModel(
            name='CollateralImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='collateral_images/')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loans.collateral')),
            ],
        ),
    ]
